/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.Controlador;
import java.awt.Color;
import java.awt.Font;

/**
 *
 * @author Josechavez
 */
public class AlquilarHabitacion extends javax.swing.JInternalFrame {
Controlador control = new Controlador();
    /**
     * Creates new form AlquilarHabitacion
     */
    public AlquilarHabitacion() {
        initComponents();
        control.cargartablaDisponible(disponible);
       disponible.getTableHeader().setFont(new Font("Cambria", 1, 16)); 
        disponible.getTableHeader().setBackground(new Color(69,90,100));
//        disponible.getTableHeader().setForeground(Color.white);
//        disponible.setRowHeight(disponible.getRowHeight());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        disponible = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        PUtilizar = new javax.swing.JPanel();
        lblUtilizar = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();

        setBackground(new java.awt.Color(207, 216, 220));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setBackground(new java.awt.Color(255, 82, 82));
        jLabel9.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(33, 33, 33));
        jLabel9.setText("Disponibles.");

        disponible.setBackground(new java.awt.Color(255, 255, 255));
        disponible.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        disponible.setForeground(new java.awt.Color(0, 0, 0));
        disponible.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "N-HAB", "TIPO", "PRECIO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        disponible.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_LAST_COLUMN);
        disponible.setAutoscrolls(false);
        disponible.setGridColor(new java.awt.Color(0, 0, 0));
        disponible.setSelectionBackground(new java.awt.Color(255, 51, 51));
        disponible.setSelectionForeground(new java.awt.Color(255, 255, 255));
        disponible.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        disponible.setSurrendersFocusOnKeystroke(true);
        disponible.getTableHeader().setReorderingAllowed(false);
        disponible.setUpdateSelectionOnSort(false);
        disponible.setVerifyInputWhenFocusTarget(false);
        jScrollPane1.setViewportView(disponible);
        if (disponible.getColumnModel().getColumnCount() > 0) {
            disponible.getColumnModel().getColumn(0).setResizable(false);
            disponible.getColumnModel().getColumn(1).setResizable(false);
            disponible.getColumnModel().getColumn(2).setResizable(false);
        }

        jLabel10.setBackground(new java.awt.Color(255, 82, 82));
        jLabel10.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(33, 33, 33));
        jLabel10.setText("En uso");

        PUtilizar.setBackground(new java.awt.Color(69, 90, 100));
        PUtilizar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        PUtilizar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblUtilizar.setBackground(new java.awt.Color(69, 90, 100));
        lblUtilizar.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        lblUtilizar.setForeground(new java.awt.Color(255, 255, 255));
        lblUtilizar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUtilizar.setText("  Utilizar");
        lblUtilizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblUtilizarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblUtilizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblUtilizarMouseExited(evt);
            }
        });
        PUtilizar.add(lblUtilizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 40));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 336, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(3, 3, 3)
                        .addComponent(PUtilizar, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 492, Short.MAX_VALUE)
                        .addComponent(jLabel10)
                        .addGap(358, 358, 358))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PUtilizar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jDesktopPane1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 506, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblUtilizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUtilizarMouseClicked
 
    }//GEN-LAST:event_lblUtilizarMouseClicked

    private void lblUtilizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUtilizarMouseEntered
         control.efectoColocarColor(PUtilizar);
    }//GEN-LAST:event_lblUtilizarMouseEntered

    private void lblUtilizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUtilizarMouseExited

        control.resetColorMovimiento(PUtilizar,PUtilizar,lblUtilizar);

    }//GEN-LAST:event_lblUtilizarMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PUtilizar;
    private javax.swing.JTable disponible;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblUtilizar;
    // End of variables declaration//GEN-END:variables
}
