/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.Consultar;
import controlador.Controlador;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author Josechavez
 */
public class Consulta extends javax.swing.JInternalFrame {

    Controlador c = new Controlador();
    Consultar cons = new Consultar(this);

    /**
     * Creates new form Consulta
     */
    public Consulta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        PVentas = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        lblVentas = new javax.swing.JLabel();
        PEmpleado = new javax.swing.JPanel();
        lblEmpleado = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        PCaja = new javax.swing.JPanel();
        lblFlujo = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        PVentasE = new javax.swing.JPanel();
        lblVentas1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        mostar = new javax.swing.JDesktopPane();

        setBackground(new java.awt.Color(207, 216, 220));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));

        PVentas.setBackground(new java.awt.Color(255, 255, 255));
        PVentas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 82, 82), 5));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Document_32px.png"))); // NOI18N

        lblVentas.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        lblVentas.setForeground(new java.awt.Color(255, 82, 82));
        lblVentas.setText("Ventas .");
        lblVentas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblVentasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblVentasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblVentasMouseExited(evt);
            }
        });

        javax.swing.GroupLayout PVentasLayout = new javax.swing.GroupLayout(PVentas);
        PVentas.setLayout(PVentasLayout);
        PVentasLayout.setHorizontalGroup(
            PVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PVentasLayout.createSequentialGroup()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        PVentasLayout.setVerticalGroup(
            PVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblVentas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        PEmpleado.setBackground(new java.awt.Color(255, 255, 255));
        PEmpleado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 82, 82), 5));

        lblEmpleado.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        lblEmpleado.setForeground(new java.awt.Color(255, 82, 82));
        lblEmpleado.setText("Empleados.");
        lblEmpleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEmpleadoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblEmpleadoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblEmpleadoMouseExited(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Document_32px.png"))); // NOI18N

        javax.swing.GroupLayout PEmpleadoLayout = new javax.swing.GroupLayout(PEmpleado);
        PEmpleado.setLayout(PEmpleadoLayout);
        PEmpleadoLayout.setHorizontalGroup(
            PEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PEmpleadoLayout.createSequentialGroup()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
        );
        PEmpleadoLayout.setVerticalGroup(
            PEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblEmpleado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        PCaja.setBackground(new java.awt.Color(255, 255, 255));
        PCaja.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 82, 82), 5));

        lblFlujo.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        lblFlujo.setForeground(new java.awt.Color(255, 82, 82));
        lblFlujo.setText("Flujo de caja.");
        lblFlujo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFlujoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblFlujoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblFlujoMouseExited(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Document_32px.png"))); // NOI18N

        javax.swing.GroupLayout PCajaLayout = new javax.swing.GroupLayout(PCaja);
        PCaja.setLayout(PCajaLayout);
        PCajaLayout.setHorizontalGroup(
            PCajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PCajaLayout.createSequentialGroup()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblFlujo, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
        );
        PCajaLayout.setVerticalGroup(
            PCajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PCajaLayout.createSequentialGroup()
                .addGroup(PCajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(lblFlujo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel9.setBackground(new java.awt.Color(255, 82, 82));
        jLabel9.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(33, 33, 33));
        jLabel9.setText("Consultar. ");

        PVentasE.setBackground(new java.awt.Color(255, 255, 255));
        PVentasE.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 82, 82), 5));

        lblVentas1.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        lblVentas1.setForeground(new java.awt.Color(255, 82, 82));
        lblVentas1.setText("Ventas por empelado.");
        lblVentas1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblVentas1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblVentas1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblVentas1MouseExited(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Document_32px.png"))); // NOI18N

        javax.swing.GroupLayout PVentasELayout = new javax.swing.GroupLayout(PVentasE);
        PVentasE.setLayout(PVentasELayout);
        PVentasELayout.setHorizontalGroup(
            PVentasELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PVentasELayout.createSequentialGroup()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblVentas1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        PVentasELayout.setVerticalGroup(
            PVentasELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
            .addComponent(lblVentas1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PVentasE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(PCaja, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PVentasE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PVentas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PEmpleado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PCaja, javax.swing.GroupLayout.PREFERRED_SIZE, 52, Short.MAX_VALUE))
                .addGap(58, 58, 58))
        );

        mostar.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout mostarLayout = new javax.swing.GroupLayout(mostar);
        mostar.setLayout(mostarLayout);
        mostarLayout.setHorizontalGroup(
            mostarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        mostarLayout.setVerticalGroup(
            mostarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 492, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mostar))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(mostar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblEmpleadoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEmpleadoMouseEntered
        if (cons.Empleado == false) {
            c.EfectoLabel(PEmpleado, lblEmpleado);
        }

    }//GEN-LAST:event_lblEmpleadoMouseEntered

    private void lblEmpleadoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEmpleadoMouseExited
        if (cons.Empleado == false) {
            c.EfectoQuitarLabel(PEmpleado, lblEmpleado);
        }
    }//GEN-LAST:event_lblEmpleadoMouseExited

    private void lblVentasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVentasMouseEntered
        if (cons.Venta == false) {
            c.EfectoLabel(PVentas, lblVentas);
        }

    }//GEN-LAST:event_lblVentasMouseEntered

    private void lblVentasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVentasMouseExited
        if (cons.Venta == false) {
            c.EfectoQuitarLabel(PVentas, lblVentas);

        }

    }//GEN-LAST:event_lblVentasMouseExited

    private void lblFlujoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFlujoMouseEntered
        if (cons.Caja == false) {
            c.EfectoLabel(PCaja, lblFlujo);
        }

    }//GEN-LAST:event_lblFlujoMouseEntered

    private void lblFlujoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFlujoMouseExited
        if (cons.Caja == false) {
            c.EfectoQuitarLabel(PCaja, lblFlujo);
        }

    }//GEN-LAST:event_lblFlujoMouseExited

    private void lblVentas1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVentas1MouseEntered
        if (cons.VenteEm == false) {
            c.EfectoLabel(PVentasE, lblVentas1);
        }
    }//GEN-LAST:event_lblVentas1MouseEntered

    private void lblVentas1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVentas1MouseExited
        if (cons.VenteEm == false) {
            c.EfectoQuitarLabel(PVentasE, lblVentas1);
        }

    }//GEN-LAST:event_lblVentas1MouseExited

    private void lblEmpleadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEmpleadoMouseClicked
        tabla_empleado tabla = new tabla_empleado();
        c.mostrar(mostar, tabla);
        c.EfectoLabel(PEmpleado, lblEmpleado);
        cons.activar(true, false, false, false);
        cons.resetColorJPanel(new JPanel[]{PVentas, PVentasE, PCaja});
        cons.resetColorLabel(new JLabel[]{lblVentas, lblFlujo, lblVentas1});
    }//GEN-LAST:event_lblEmpleadoMouseClicked

    private void lblVentasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVentasMouseClicked
        c.EfectoLabel(PVentas, lblVentas);
        cons.activar(false, true, false, false);
        cons.resetColorJPanel(new JPanel[]{PEmpleado, PVentasE, PCaja});
        cons.resetColorLabel(new JLabel[]{lblEmpleado, lblFlujo, lblVentas1});

    }//GEN-LAST:event_lblVentasMouseClicked

    private void lblVentas1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVentas1MouseClicked
        c.EfectoLabel(PVentasE, lblVentas1);
        cons.activar(false, false, true, false);
        cons.resetColorJPanel(new JPanel[]{PEmpleado, PVentas, PCaja});
        cons.resetColorLabel(new JLabel[]{lblEmpleado, lblFlujo, lblVentas});
    }//GEN-LAST:event_lblVentas1MouseClicked

    private void lblFlujoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFlujoMouseClicked
        c.EfectoLabel(PCaja, lblFlujo);
        cons.activar(false, false, false, true);
        cons.resetColorJPanel(new JPanel[]{PEmpleado, PVentas, PVentasE});
        cons.resetColorLabel(new JLabel[]{lblEmpleado, lblVentas1, lblVentas});
    }//GEN-LAST:event_lblFlujoMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PCaja;
    private javax.swing.JPanel PEmpleado;
    private javax.swing.JPanel PVentas;
    private javax.swing.JPanel PVentasE;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblEmpleado;
    private javax.swing.JLabel lblFlujo;
    private javax.swing.JLabel lblVentas;
    private javax.swing.JLabel lblVentas1;
    private javax.swing.JDesktopPane mostar;
    // End of variables declaration//GEN-END:variables
}
